### PR TITLE
Milestone Friendships v2

### PR DESCRIPTION
**Pull request by Milypm**
For this milestone:
- Add logic to see the “Timeline” page with posts written by me and all my friends.
- Create a method for showing the number of Likes of a post.

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Changes Required
**Hello team, great job on this milestone**

### Highlight
- Well done on the linter configuration
- Well done on the descriptive commit messages
- Great Job with the unit and integration test

### To improve
- [x] There is an error while running the migrations. Kindly check the order of the migrations and ensure that the friendship model is created first before the update.

Keep in mind about the fat models and skinny controller? [READ ABOUT](https://www.sitepoint.com/10-ruby-on-rails-best-practices/#:~:text=Arguably%20one%20of%20the%20most,in%20a%20nice%2C%20testable%20method.)

- [x] Check to ensure that when friendship is confirmed, an additional row with reversed user-friend pair is created. Use [this article](https://explainextended.com/2009/03/07/selecting-friends/) and [Stackoverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) as hints
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [x] thanks to this, we can find user friends only by user_id in friendships table

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

- [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

Kindly implement the above changes before submitting another code review.

### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
## HAPPY CODING 
_Slack: Oloo Moses_

**Comment by Milypm** [comment]
> # Changes Required
> 
> **Hello team, great job on this milestone**
> ### Highlight
> 
>     * Well done on the linter configuration
> 
>     * Well done on the descriptive commit messages
> 
>     * Great Job with the unit and integration test
> 
> 
> ### To improve
> 
>     * [ ]  There is an error while running the migrations. Kindly check the order of the migrations and ensure that the friendship model is created first before the update.
> 
> 
> Keep in mind about the fat models and skinny controller? [READ ABOUT](https://www.sitepoint.com/10-ruby-on-rails-best-practices/#:~:text=Arguably%20one%20of%20the%20most,in%20a%20nice%2C%20testable%20method.)
> 
>     * [x]  Check to ensure that when friendship is confirmed, an additional row with reversed user-friend pair is created. Use [this article](https://explainextended.com/2009/03/07/selecting-friends/) and [Stackoverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) as hints
> 
> 
> ```ruby
> def confirm_friend
>   self.update_attributes(confirmed: true)
>   Friendship.create!(friend_id: self.user_id,
>                   user_id: self.friend_id,
>                   confirmed: true)
> end
> ```
> 
>     * [x]  thanks to this, we can find user friends only by user_id in friendships table
> 
> 
> ```ruby
> # User model
> 
> has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
> has_many :friends, through: :confirmed_friendships
> ```
> 
>     * [x]  User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
> 
> 
> ```ruby
> # User model
> 
> # Users who needs to confirm friendship
> has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
> has_many :pending_friends, through: :pending_friendships, source: :friend
> ```
> 
>     * [x]  User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
> 
> 
> ```ruby
> # User model
> 
> # Users who requested to be friends (needed for notifications)
> has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
> has_many :friend_requests, through: :inverted_friendships
> ```
> 
>     * [x]  in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)
> 
> 
> ```ruby
> # User model
> 
> def friends_and_own_posts
>   Post.where(user: (self.friends.to_a << self))
>   # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
> end
> ```
> 
> Kindly implement the above changes before submitting another code review.
> ### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
> ## HAPPY CODING
> 
> _Slack: Oloo Moses_

Hi Oloo,

Thank you for your complete and helpful review, I already worked on most of the features that you mention.
I just have one doubt regarding the error with the migrations (the first point to improve that you mention).
I think that the issue is related to the fact that I did a rollback to the migration, actually, I'm a bit lost here since I don't have a lot of experience managing databases, so if you could help me out with this, I would really appreciate it.
These are the last 6 migrations I created and that are located in the 'db/migrate' directory:

- 20210226162813_add_user_to_friendships
- 20210226163638_add_friend_id_to_friendships
- 20210226163744_add_status_to_friendships
- 20210226175628_change_column_default
- 20210226180804_drop_friendships_table
- 20210226181107_create_friendships

Thank you once again.
Mily.

**Comment by Milypm** [comment]
> Hi Oloo,
> 
> Thank you for your complete and helpful review, I already worked on most of the features that you mention.
> I just have one doubt regarding the error with the migrations (the first point to improve that you mention).
> I think that the issue is related to the fact that I did a rollback to the migration, actually, I'm a bit lost here since I don't have a lot of experience managing databases, so if you could help me out with this, I would really appreciate it.
> These are the last 6 migrations I created and that are located in the 'db/migrate' directory:
> 
>     * 20210226162813_add_user_to_friendships
> 
>     * 20210226163638_add_friend_id_to_friendships
> 
>     * 20210226163744_add_status_to_friendships
> 
>     * 20210226175628_change_column_default
> 
>     * 20210226180804_drop_friendships_table
> 
>     * 20210226181107_create_friendships
> 
> 
> Thank you once again.
> Mily.

@oloomoses 
(Sorry, forgot to tag you within the comment)

**Comment by oloomoses** [comment]
> > Hi Oloo,
> > Thank you for your complete and helpful review, I already worked on most of the features that you mention.
> > I just have one doubt regarding the error with the migrations (the first point to improve that you mention).
> > I think that the issue is related to the fact that I did a rollback to the migration, actually, I'm a bit lost here since I don't have a lot of experience managing databases, so if you could help me out with this, I would really appreciate it.
> > These are the last 6 migrations I created and that are located in the 'db/migrate' directory:
> > ```
> > * 20210226162813_add_user_to_friendships
> > 
> > * 20210226163638_add_friend_id_to_friendships
> > 
> > * 20210226163744_add_status_to_friendships
> > 
> > * 20210226175628_change_column_default
> > 
> > * 20210226180804_drop_friendships_table
> > 
> > * 20210226181107_create_friendships
> > ```
> > 
> > 
> > Thank you once again.
> > Mily.
> 
> @oloomoses
> (Sorry, forgot to tag you within the comment)

`create_friendships` should come before:
```
20210226162813_add_user_to_friendships
20210226163638_add_friend_id_to_friendships
20210226163744_add_status_to_friendships
```
The issue is just with the order of the migration

**Comment by Milypm** [comment]
> > > Hi Oloo,
> > > Thank you for your complete and helpful review, I already worked on most of the features that you mention.
> > > I just have one doubt regarding the error with the migrations (the first point to improve that you mention).
> > > I think that the issue is related to the fact that I did a rollback to the migration, actually, I'm a bit lost here since I don't have a lot of experience managing databases, so if you could help me out with this, I would really appreciate it.
> > > These are the last 6 migrations I created and that are located in the 'db/migrate' directory:
> > > ```
> > > * 20210226162813_add_user_to_friendships
> > > 
> > > * 20210226163638_add_friend_id_to_friendships
> > > 
> > > * 20210226163744_add_status_to_friendships
> > > 
> > > * 20210226175628_change_column_default
> > > 
> > > * 20210226180804_drop_friendships_table
> > > 
> > > * 20210226181107_create_friendships
> > > ```
> > > 
> > > 
> > > Thank you once again.
> > > Mily.
> > 
> > 
> > @oloomoses
> > (Sorry, forgot to tag you within the comment)
> 
> `create_friendships` should come before:
> 
> ```
> 20210226162813_add_user_to_friendships
> 20210226163638_add_friend_id_to_friendships
> 20210226163744_add_status_to_friendships
> ```
> 
> The issue is just with the order of the migration

Thank you! @oloomoses

**Review by SmithVyne — CHANGES_REQUESTED** [review]
### Changes Required
Hi @Milypm. I feel your project is great but you have really serious issues with your migrations. Try going over them and find what you missed out. It could really help. Currently, so many things do not work.

Use this [document as a reference.](https://edgeguides.rubyonrails.org/active_record_migrations.html) Read all of it to understand Active Record migrations fully, then find your faults and fix them.

Make these changes and request another code review. You should get it approved this time.

You can also reach out to me on slack, **@SmithVyne** if you have any other questions.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ⚠️**

<hr>

hello there 🙂
I see you've not made any changes after the last review, please implement the requested changes before asking for another CRR. 

good luck and happy coding 👍

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔**
Great work on this project👏👏👏👏👏
You can merge
Happy coding💻💻💻💻

**Pull request merged**
